version: '2'
services:

  app:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/news_analysis-hunter_gatherer:production
    volumes:
      - ../app:/app
    depends_on:
      - queue

  queue:
    image: redis
    volumes:
      - ../data:/data
    ports:
      - 6379:6379
