version: '2'
services:

  queue:
    hostname: queue
    image: rabbitmq:3.6.10-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - log_levels=warning
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672
      - 15672
      - 8080

  result:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379

  storage:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=mysecretuser
      - POSTGRES_DB=media_uncovered
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

  worker:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/news_analysis-hunter_gatherer:worker
    environment:
      - QUEUE_USER=admin
      - QUEUE_PASSWORD=mypass
      - QUEUE_HOST=queue
      - QUEUE_PORT=5672
      - DATABASE_NAME=media_uncovered
      - DATABASE_USER=mysecretuser
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_HOST=storage
      - DATABASE_PORT=5432
      - RESULT_HOST=result
      - RESULT_PORT=6379
    depends_on:
      - queue
      - result
      - storage
    links:
      - queue:queue
      - storage:storage
      - result:result
    command: celery worker -A pipes --loglevel=warning --prefetch-multiplier=64 --task-events

  monitor:
    build:
      context: ..
      dockerfile: deployment/monitor/Dockerfile
    image: todorus/news_analysis-hunter_gatherer:monitor
    ports:
     - "5555:5555"
    environment:
     - QUEUE_USER=admin
     - QUEUE_PASSWORD=mypass
     - QUEUE_HOST=queue
     - QUEUE_PORT=5672
     - DATABASE_NAME=media_uncovered
     - DATABASE_USER=mysecretuser
     - DATABASE_PASSWORD=mysecretpassword
     - DATABASE_HOST=storage
     - DATABASE_PORT=5432
     - RESULT_HOST=result
     - RESULT_PORT=6379
    depends_on:
      - queue
      - result
    command: bash -c "sleep 10s; flower -A pipes --port=5555 --broker=amqp://admin:mypass@queue:5672//;"
