version: '2'
services:

  queue:
    hostname: queue
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672

  result:
    image: redis
    volumes:
      - ../data/redis:/data
    ports:
      - 6379

  storage:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=mysecretuser
      - POSTGRES_DB=media_uncovered
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ../data/storage:/var/lib/postgresql/data
    ports:
      - 5432

  seeder:
    build:
      context: ..
      dockerfile: deployment/app/Dockerfile
    image: todorus/news_analysis-hunter_gatherer:production
    environment:
      - DATABASE_NAME=media_uncovered
      - DATABASE_USER=mysecretuser
      - DATABASE_PASSWORD=mysecretpassword
    depends_on:
      - queue
      - result
      - storage
    links:
      - queue:queue
      - storage:storage
      - result:result
    command: python3 seed.py
