version: '2'
services:

  test:
    build:
      context: ..
      dockerfile: deployment/test/Dockerfile
    image: todorus/news_analysis-hunter_gatherer:test
    volumes:
      - ../reports:/frame/results
